create html
nanakusa27/masaki-watanabe pull request #1
Opened 2020-04-07 10:29 UTC by nanakusa27

- nri の index.htmlを作成いたしました。
- classはcssにより変更することもあります。

2020-04-15 06:22 UTC, nanakusa27 commented
htmlのみの提出です。
一度本に戻ってから、作り変えたので全体的に変わっております。
コードチェッカー通して問題ありませんでした。
やってないこと
- レスポンシブデザイン
- ハンバーガーメニュー
- css

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +        <small>copyright(c) Nomura Research Institute, Ltd. All rights resarved</small>
「All rights resarved」はtypo（誤字）で「All right reserved」が正しいです。
こちらの修正をお願いします。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +            <li><a href="#">人材の育成</a></li>
「経営方針」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「経営方針」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +        </ul>
「企業案内」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「企業案内」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +            <li><a href="#">業界トップクラスの収益力</a></li>
「NRIの強み」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「NRIの強み」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +            <li><a href="#">その他関連会社・団体</a></li>
「NRIグループ国内・海外拠点一覧」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「NRIグループ国内・海外拠点一覧」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +        </ul>
「事業案内」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「事業案内」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">用語解説</a></li>
「ナレッジ・インサイト」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「ナレッジ・インサイト」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">未来創発センター</a></li>
「ソリューション・サービス」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「ソリューション・サービス」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">ライブラリ</a></li>
「サステナビリティ」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「サステナビリティ」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">イベント</a></li>
「ニュース」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「ニュース」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">国内・海外拠</a>点</li>
「企業情報」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「企業情報」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:08 UTC, choimake commented on nri/index.html
> +                <li><a href="#">個人投資家の皆さまへ</a></li>
「株主・投資家情報(IR)」はリストの中の項目ではなく、リストのタイトルのような位置付けの意味合いです。
「株主・投資家情報(IR)」の項目をリストのタイトルを`ul`タグの外に記述するような形に修正してください。

2020-04-15 07:09 UTC, choimake commented
コメントしましたので確認お願いします。

2020-04-15 07:38 UTC, nanakusa27 commented
指摘部分、修正いたしました！
・listのタイトル部分をulの外に出しました。
・意味のあるまとまりになると思うのでdivで囲みました。

2020-04-15 08:40 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-04-15 08:40 UTC, choimake commented on nri/index.html
> +                </ul>
「ナレッジ・インサイト」、「ソリューション・サービス」、「サステナビリティ」、「ニュース」、「企業情報」、「株主・投資家情報(IR)」に関しては、リスト内に入れてリンクにしてください。
これは私の前回の指摘が間違っておりました。申し訳ありませんがよろしくお願いします。

2020-04-15 08:40 UTC, choimake commented on nri/index.html
> +        <small>copyright(c) Nomura Research Institute, Ltd. All right resarved</small>
修正内容が間違っています。
「All right resarved」ではなく「All rights reserved」が正しいです。

上記の内容で修正してください。

2020-04-15 09:02 UTC, nanakusa27 commented
- 誤字の修正
- footer-listの修正、リンク付

2020-04-15 09:14 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +<link rel="stylesheet" href="style.css">
インデントつけましょう

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +            <li><a href="#">株主•投資家情報(IR)</a></li>
ここの中黒丸が他のものと違うので合わせましょう

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +</nav>
`main`タグ内に含めましょう

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +            <a href="#"><img src="images/icon-linkedin.svg" alt="リクトイン"></a>
細かいですがリンクトインですね

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +</nav>
ここも`main`タグ内に含めましょう

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +        </div><!-- /.footer-list -->
`footer`かというと微妙なところなので免責事項～を`footer`にして、それより前は`main`に含めましょう

2020-04-15 09:14 UTC, piasoratech commented on nri/index.html
> +            <p><a href="#">サイトマップ</a></p>
listでもいいかと思います

2020-04-15 10:01 UTC, nanakusa27 commented
- head内にインデントを付けました。
- nav、bottom-list(元footer)をmainに含めました。
- bottom-listの一番下のpの集まりをlistにしました。
- リクトイン→リンクトイン
-20行目の黒丸、修正

2020-04-16 02:24 UTC, piasoratech approved these changes
良いかと！次に進みましょう！

2020-04-17 05:41 UTC, merged