Css kaguya
nanakusa27/masaki-watanabe pull request #4
Opened 2020-04-22 01:27 UTC by nanakusa27

2020-04-22 01:29 UTC, nanakusa27 commented
kaguya-css-homeを作成いたしました。
コードチェッカー問題ありませんでした。

やってないこと
・レスポンシブ対応
・home以外のcss

2020-04-22 04:25 UTC, yusaku-inamura requested changes
レビューしたので確認お願いします。

2020-04-22 04:25 UTC, yusaku-inamura commented on kaguya/index.html
> +        <section class="container">
ここの `section` ですが、こちらは見た感じ装飾目的で
実はクラスを付与してのレイアウト目的なら `div` を使用するのが推奨されています。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/section
MDNで調べても下記のように記載されていますね。
> <section> 要素を単なる汎用コンテナーとして使用しないでください。このような場合、特にスタイル付けのみの目的で区切るのは <div> の役割です。大まかに言えば、 section は文書のアウトラインに論理的に現れるものに使用してください。

今回の文章をアウトラインした場合、この単位のsectionは存在しないように見えますね。
目次とかイメージしてもらえるとわかりやすいかも。

2020-04-22 04:25 UTC, yusaku-inamura commented on kaguya/index.html
> +                        <p><input type="submit" name="submit" value="SEND" class="btn input-send"></p>
ここ余計な枠線ついちゃってますね。
枠線消しちゃいましょうか。
あとhover時の効果も足りてないように見えます。
XDで確認して実装してみてください。

2020-04-22 04:25 UTC, yusaku-inamura commented on kaguya/index.html
> +                        srcset="images/logo_footer.png 1x, images/logo_footer@2x.png 2x"></a>
(対応しなくてもOK)
imgタグなどそもそも閉じタグが存在しないタグに関しては末尾に `/` を追加するのも良いですね。
単純に閉じタグがないことを明示的に示してみやすくする以上の理由は今の所ないはずですが。
```html
<img src="images/logo_footer.png" alt="HTMLCSS" srcset="images/logo_footer.png 1x, images/logo_footer@2x.png 2x" />
```

2020-04-22 04:25 UTC, yusaku-inamura commented on kaguya/style.css
> +    background: #fcfcfc;
正直修正の必要はないと思いますが、カラーだけの指定なら `background-color` 使ってもいいかなあと。

2020-04-22 04:52 UTC, nanakusa27 commented
kaguya-css-home
sectionタグをdivタグに変更いたしました。
ボタンのhover要素の追加いたしました。

2020-04-22 05:21 UTC, choimake commented
対応ありがとうございました。LGTMです。

2020-04-22 08:45 UTC, nanakusa27 commented
news,recruit,contact、css対応しました。
コードチェッカー問題ありませんでした。

やってないこと
・レスポンシブ対応

2020-04-22 09:09 UTC, choimake reviewed
コメントしましたので、確認お願いします。

- 「名前」「メールアドレス」「お問い合わせ」のフォントがXDのデータと異なっています。
こちら修正お願いします。

<img width="630" alt="スクリーンショット 2020-04-22 18 02 28" src="https://user-images.githubusercontent.com/52233450/79963308-2b1d0500-84c4-11ea-84b9-6f12d44ea2c2.png">

2020-04-22 09:09 UTC, choimake commented on kaguya/style.css
> +    font-family: 'Noto Sans JP', sans-serif;
XDのデータを確認したところフォントの種類は「Noto Sans JP」ではなく「Noto Sans」です。
前回の指摘漏れに当たる部分で申し訳ありません。
お手数ですが修正お願いします。

2020-04-22 09:09 UTC, choimake commented on kaguya/style.css
> +    color: #3B3B3B;
カラーコードの指定が大文字と小文字が混ざっています。
どちらかの形式に統一するよう修正してください。
※他にも該当箇所があるので、合わせて修正お願いします。

2020-04-22 12:25 UTC, nanakusa27 commented
指摘箇所、修正いたしました。

2020-04-23 02:48 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-04-23 02:48 UTC, choimake commented on kaguya/style.css
> +   width: 144px;
インデントがこの部分だけズレているので修正お願いします。
前回の指摘漏れで申し訳ありません。対応お願いします。

2020-04-23 02:51 UTC, nanakusa27 commented
指摘箇所修正いたしました！

2020-04-23 04:36 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-04-23 04:36 UTC, choimake commented on kaguya/style.css
> +   width: 144px;
すいません。
`width: 144px`のところのインデントが「3」になっているので、これを「4」に修正お願いします。

2020-04-23 04:42 UTC, nanakusa27 commented
インデント正しく修正できました。

2020-04-23 05:29 UTC, choimake commented
お疲れ様でした。LGTMです。

2020-04-23 12:50 UTC, merged